# Generated by Django 4.0.3 on 2022-07-15 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportGiornaliero',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Data', models.DateField()),
                ('Pasto', models.CharField(max_length=25)),
                ('Ha_dormito', models.BooleanField()),
                ('Bisogni_fisiologici', models.CharField(max_length=250)),
                ('Promemoria_genitori', models.CharField(max_length=500)),
                ('Inviato', models.BooleanField()),
                ('Modificato', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sezione',
            fields=[
                ('Nome', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Email_Rappresentante', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('TestingID', models.AutoField(primary_key=True, serialize=False)),
                ('TestingName', models.CharField(max_length=500)),
                ('TestingSurname', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Bambini',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=85)),
                ('Cognome', models.CharField(max_length=30)),
                ('Email_Genitore1', models.EmailField(max_length=254)),
                ('Email_Genitore2', models.EmailField(max_length=254)),
                ('Data_di_nascita', models.DateField()),
                ('Orario_uscita', models.DateTimeField()),
                ('Avatar', models.BinaryField()),
                ('IDReport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passidoro_app.reportgiornaliero')),
                ('NomeSezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passidoro_app.sezione')),
            ],
        ),
    ]
