# Generated by Django 4.0.3 on 2022-07-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passidoro_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bambini',
            name='Avatar',
            field=models.CharField(max_length=500),
        ),
    ]
