# Generated by Django 4.0.3 on 2022-07-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passidoro_app', '0002_alter_bambini_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bambini',
            name='Data_di_nascita',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bambini',
            name='Orario_uscita',
            field=models.CharField(max_length=500),
        ),
    ]
