# Generated by Django 4.0.3 on 2022-07-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passidoro_app', '0003_alter_bambini_data_di_nascita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportgiornaliero',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
