# Generated by Django 4.0.3 on 2022-08-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passidoro_app', '0004_alter_reportgiornaliero_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bambini',
            name='Email_Genitore1',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bambini',
            name='Email_Genitore2',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
