# Generated by Django 4.0.3 on 2022-08-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passidoro_app', '0005_alter_bambini_email_genitore1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileData', models.FileField(upload_to='')),
            ],
        ),
    ]
