# Generated by Django 4.0.3 on 2022-08-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passidoro_app', '0006_testingfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingfile',
            name='FileData',
            field=models.FileField(upload_to='images'),
        ),
    ]
