# Generated by Django 4.0.3 on 2022-08-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passidoro_app', '0007_alter_testingfile_filedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordCode',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('code_to_sent', models.IntegerField()),
            ],
        ),
    ]
